appVersion: 1.14.2
appName: online

message: "Welcome Florida"
tenant: florida

resources:
  pod:
    memoryRequest: "100Mi" # 8GB
    memoryLimit: "200Mi"
  
  namespace:
    podLimit: 20
    memoryLimit: 4GI
    cpuLimit: 4
